name: "Create GitHub Secret"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environemnt for the secret"
        required: true
        type: choice
        options:
          - "production"
          - "development"
      secret_name:
        description: "Name of the secret"
        required: true
      secret_value:
        description: "Value of the secret"
        required: true

jobs:
  create_github_secret:
    name: "Create GitHub Secret"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          name: ${{ github.event.inputs.secret_name }}
          value: ${{ github.event.inputs.secret_value }}
          pa_token: ${{ secrets.PA_TOKEN }}
