name: CI

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::239995296586:role/GitHubAction-SSMAdmin

      - name: Retrieve App Secrets from AWS Parameter Store
        uses: gsf/aws-params-env-action@v1
        with:
          params: |
            APP_SECRETS=${{vars.APP_SECRETS_SSM_ARN}}

      - name: Verify App Secrets
        run: echo ${{env.APP_SECRETS}}

      - uses: actions/checkout@v3
      - name: Build & Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          DIRECTORY: rental-system-backend
          BRANCH: ${{github.head_ref}}
          APP_SECRETS: ${{env.APP_SECRETS}}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          envs: DIRECTORY, BRANCH, APP_SECRETS
          script_stop: true
          script: |
            # Remove the directory if it exists
            if [ -d "$DIRECTORY" ]; then
              rm -rf "$DIRECTORY"
            fi

            echo $BRANCH

            # Clone the repository
            git clone https://github.com/bkrental/rental-system-backend.git "$DIRECTORY"
            cd "$DIRECTORY"

            # Config git
            git config --global user.email "datdev2409@gmail.com"
            git config --global user.name "remote-server"

            git checkout -b "$BRANCH"
            git pull origin "$BRANCH"

            yarn --version
            yarn install

            sudo cp ./nginx.dev.conf /etc/nginx/nginx.conf
            sudo systemctl restart nginx

            # Create ENV file
            rm -f .env.dev
            echo "$APP_SECRETS" > .env.dev

            yarn dev

      - name: URL Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://dev-backend.datnguyen2409.me/health
          max-attempts: 3
          retry-delay: 10s
