name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          DIRECTORY: rental-system-backend
          BRANCH: ${{github.head_ref}}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          envs: DIRECTORY, BRANCH
          script_stop: true
          script: |
            # Remove the directory if it exists
            if [ -d "$DIRECTORY" ]; then
              rm -rf "$DIRECTORY"
            fi

            echo $BRANCH

            # Clone the repository
            git clone https://github.com/bkrental/rental-system-backend.git "$DIRECTORY"
            cd "$DIRECTORY"

            # Config git
            git config --global user.email "datdev2409@gmail.com"
            git config --global user.name "remote-server"

            git checkout -b "$BRANCH"
            git pull origin "$BRANCH"

            yarn --version
            yarn install

            sudo cp ./nginx.dev.conf /etc/nginx/nginx.conf
            sudo systemctl restart nginx

            yarn dev

      - name: URL Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://dev-backend.datnguyen2409.me/health
          max-attempts: 3
          retry-delay: 10s
