name: CI

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  DOCKERHUB_REPO: congdat2409/rental-service-backend

jobs:
  build:
    name: Build & Push the Docker Image
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t ${{env.DOCKERHUB_REPO}}:${{github.sha}} .

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push image to DockerHub
        run: docker push ${{env.DOCKERHUB_REPO}}:${{github.sha}}
